name: Deploy to Nuget
on:
  release:
    types:
      - published
env:
  NuGetDirectory: ${{ github.workspace}}/nuget

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.*" # or the version you want to use

      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: ${{ env.NuGetDirectory }}

      - name: Deploy to NuGet
        run: dotnet nuget push ${{ env.NuGetDirectory }} --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.COSMOS_ENTITY_MAPPER_SECRET }} --skip-duplicate
